"""empty message

Revision ID: 501546791c58
Revises: 
Create Date: 2022-06-04 21:48:28.408797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501546791c58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=b'I00\n'),
    sa.Column('city', sa.String(length=120), nullable=b'I00\n'),
    sa.Column('state', sa.String(length=120), nullable=b'I00\n'),
    sa.Column('phone', sa.String(length=120), nullable=b'I00\n'),
    sa.Column('genres', sa.String(length=120), nullable=b'I00\n'),
    sa.Column('facebook_link', sa.String(length=120), nullable=b'I00\n'),
    sa.Column('image_link', sa.String(length=500), nullable=b'I00\n'),
    sa.Column('website_link', sa.String(length=500), nullable=b'I00\n'),
    sa.Column('description', sa.String(length=500), nullable=b'I00\n'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=b'I00\n'),
    sa.Column('city', sa.String(length=120), nullable=b'I00\n'),
    sa.Column('state', sa.String(length=120), nullable=b'I00\n'),
    sa.Column('address', sa.String(length=120), nullable=b'I00\n'),
    sa.Column('phone', sa.String(length=120), nullable=b'I00\n'),
    sa.Column('genres', sa.String(length=120), nullable=b'I00\n'),
    sa.Column('facebook_link', sa.String(length=120), nullable=b'I00\n'),
    sa.Column('image_link', sa.String(length=500), nullable=b'I00\n'),
    sa.Column('website_link', sa.String(length=500), nullable=b'I00\n'),
    sa.Column('description', sa.String(length=500), nullable=b'I00\n'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    op.drop_table('venues')
    op.drop_table('artists')
    # ### end Alembic commands ###
